client/package.json
client/src/components/RenterList/RenterList.spec.js
client/src/components/RenterList/index.js
client/src/themes/paper.js
client/src/themes/theme.js
client/yarn.lock

Created test file that passes for renter list.
Required adding one more dependency, and changing imports to materiaal-ui instead of mui. Not sure why the latter was required, maybe mui needs to be imported for the test file?
Test passes however, so we now have an example of how to write tests for components.

Working test for Renter List

---

client/src/components/AddUnit/index.js
client/src/components/LandlordProfile/index.js
client/src/components/LandlordSignup/index.js
client/src/components/MyUnits/index.js
client/src/components/RenterList/index.js
client/src/components/RenterProfile/index.js
client/src/components/RenterSignup/index.js
client/src/components/SearchUnits/index.js

Created the front end for inputting personal/contact information and connected it to the database.
Created the form to input values when creating a new unit posting.

Add Posting & Create Renter & Create Landlord

---

routes/addInterest.js
routes/addLandlord.js
routes/addPosting.js
routes/addRenter.js
routes/getAllUnits.js
routes/getInterestedRenters.js
routes/getLandlordProfileInfo.js
routes/getLandlordUserID.js
routes/getMyUnits.js
routes/getPostingInfo.js
routes/getRenterProfileInfo.js
routes/getRenterUserID.js
routes/getRenters.js
server.js

Changed the server.js file to route to individual files for each API so server.js is not as long.

Restructured APIs

---

client/src/components/RenterList/index.js
client/src/components/SearchUnits/index.js
routes/addInterest.js
routes/addLandlord.js
routes/addPosting.js
routes/addRenter.js
routes/getAllUnits.js
routes/getFilteredUnits.js
routes/getInterestedRenters.js
routes/getLandlordProfileInfo.js
routes/getLandlordUserID.js
routes/getMyUnits.js
routes/getPostingInfo.js
routes/getRenterUserID.js
routes/getRenters.js
server.js

Added sort units, refactored renterList and SearchUnits files. Made some fixes to server and routing, including new sql command

Sort units

---

client/src/components/RenterLogin/index.js
client/src/components/RenterProfile/index.js
client/src/components/SearchRenters/index.js
client/src/components/SearchUnits/index.js

I connected the renter pages to the firebase UserContext

connected renter to firebase

---

client/src/components/Home/index.js

I added a new title on the home page

Created new title on home page

---

client/src/components/SearchUnits/index.js
routes/getFilteredUnits.js

Filters by price, # of bedrooms, # of bathrooms with some refactoring done to separate components

Unit filters

---

client/src/components/MyUnits/index.js

I connected the delete button to the database. I could not get the dialog box to work correctly, so the current solution does not allow users to change their minds when deleting. Also, I added a prop to the AppPaper component to fix the text colour but the navbar still changes colours sometimes.

Implemented delete button connection to database

---

client/src/components/AddUnit/index.js
client/src/components/GeneralResources/navButton.js
client/src/components/Home/index.js
client/src/components/LandlordLogout/index.js
client/src/components/LandlordProfile/index.js
client/src/components/RenterLogout/index.js
client/src/components/RenterProfile/index.js
client/src/components/SearchRenters/index.js

Home Page: 
Add Posting:
My Units:
Landlord Logout:
Community:
Renter Logout:

Updated UI and fixed some of the UI bugs

---

client/src/components/RenterList/index.js
client/src/components/SearchRenters/index.js

Fixed navbar styling

---

client/src/components/AddUnit/index.js
client/src/components/Home/index.js
client/src/components/LandlordLogin/index.js
client/src/components/LandlordLogout/index.js
client/src/components/LandlordProfile/index.js
client/src/components/LandlordSignup/index.js
client/src/components/MyUnits/index.js
client/src/components/RenterList/index.js
client/src/components/RenterLogin/index.js
client/src/components/RenterLogout/index.js
client/src/components/RenterProfile/index.js
client/src/components/RenterSignup/index.js
client/src/components/SearchRenters/index.js
client/src/themes/theme.js

Update colours and redevelop page UI

---

client/src/components/MyUnits/index.js
routes/editVisibility.js
server.js

Toggle posting visibility

---

client/src/components/SearchUnits/ListUnits.js
client/src/components/SearchUnits/UnitInfoBoth.js
routes/addInterest.js
routes/isInterested.js
server.js

Interested button

---

client/src/components/SearchUnits/SearchMenuUnits.js
client/src/components/SearchUnits/UnitInfoBoth.js
client/src/components/SearchUnits/index.js
routes/getAllUnits.js

Search All Units, and added Landlord contact info when searching units

Search all

---

client/src/components/SearchUnits/SearchMenuUnits.js
client/src/components/SearchUnits/UnitInfoBoth.js
client/src/components/SearchUnits/index.js
routes/getFilteredUnits.js

Added ability to search only interested & removed default search values

---

client/src/components/AddUnit/index.js
client/src/components/GeneralResources/alert.js
client/src/components/LandlordLogin/index.js
client/src/components/LandlordLogout/index.js
client/src/components/LandlordProfile/index.js
client/src/components/LandlordSignup/index.js
client/src/components/MyUnits/index.js
client/src/components/RenterLogin/index.js
client/src/components/RenterLogout/index.js
client/src/components/RenterProfile/index.js
client/src/components/RenterSignup/index.js
client/src/components/SearchRenters/index.js
client/src/components/SearchUnits/SearchMenuUnits.js
client/src/components/SearchUnits/index.js

Alert for both, page refreshes on signup for some reason causing it to go away, if someone can look into this, that would be great

Alert for signup and create posting

---

client/src/components/RenterList/index.js
client/src/components/SearchRenters/index.js
client/src/components/SearchUnits/SearchMenuUnits.js
routes/addFriend.js
routes/getFilteredRenters.js
routes/isFriend.js
server.js

Friend button

---

client/src/components/LandlordProfile/index.js
routes/editLandlordInfo
server.js

Allows Landlord users to edit their profile info: first and last name and phone number.

EditLandlordProfileWorking

---

client/src/components/LandlordProfile/index.js
client/src/components/RenterProfile/index.js
routes/editRenterInfo.js
server.js

Edit landlord UI

---

client/src/components/RenterProfile/index.js
routes/editRenterInfo.js
server.js

Edit renter info

---

client/src/components/SearchUnits/UnitMap.js
client/src/components/SearchUnits/index.js

- Added margins around the map
- Prevented the map from overflowing the page width

Map UI Fix
